name = "redis"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glisten = ">= 7.0.1 and < 8.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
gleam_otp = ">= 0.16.1 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
